# Generated by Django 2.1.3 on 2018-12-03 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
